services:
  - type: web
    name: fastapi-api
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: fastapi-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: fastapi-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: fastapi-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: fastapi-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: fastapi-db
          property: password
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

databases:
  - name: fastapi-db
    databaseName: fastapi_db
    user: postgres
    region: ohio
    postgresMajorVersion: "16"
